language: python
python:
- 3.6
before_install:
- ls -al
- tar xvfz secrets.tar
install:
- pip install -r requirements.txt
script:
- "./app/manage.py test"
dd:
- openssl aes-256-cbc -K $encrypted_f30e149297a7_key -iv $encrypted_f30e149297a7_iv
  -in secrets.tar.enc -out secrets.tar -d
